### ISSUE TITLE
Need Endpoint to Upload Neighborhood

### ISSUE THREAD

**Issue by hebron-george** [happy-software/happy_hood#35]
We've got tasks to:

- Generate an empty CSV for neighborhood data
- Upload valid CSV of neighborhood data
- Collect `zpid`s for houses

We need an endpoint that can take a valid CSV file in as input and upload the neighborhood into the db.
After successfully uploading the neighborhood, it should then collect the `zpid`s for all of those houses.

**Comment by hectron** [comment]
Are there any concerns around authorization/authentication for this endpoint?

**Comment by hebron-george** [comment]
Tbh I don't know much about setting up auth so I didn't even think about it.

I guess we could have users and set up an UI to upload the CSV to?

side-note: Something I've wanted to do for a while is to send a message to `HappyHood` from `HappyHouse` when someone creates a new profile for their house so that its price history could start getting tracked. But we don't get neighborhood details in `HappyHouse` so I don't know how to solve for that.

**Comment by hectron** [comment]
Kinda weird, but what if we had a way to create a hood from `HappyHouse`?

**Comment by hebron-george** [comment]
Yeah, that's a good idea.
Let's spec it out and add it to the description of this Issue?
Then it can be used for the PR to update it.

**Comment by hectron** [comment]
Resolved creating a neighborhood + houses via #51.
