### ISSUE TITLE
DailyDifferenceCalculator compare against most recently available data

### ISSUE THREAD

**Issue by hebron-george** [happy-software/happy_hood#39]
We recently had an issue where we ran out of free dyno hours with Heroku and so the daily difference message posted to slack caused the calculator to compare against "yesterday's" values which were missing since the job didn't run.

We should compare against the most recently available date.
And that date should be displayed in Slack so we know when the comparison was against.

Somethings to consider:

- What if no data is available?

**Comment by hectron** [comment]
This was released after merging in #40 . What a great improvement 💯
